### ISSUE TITLE
Error thowing on running eslint-editorconfig command

### ISSUE THREAD

**Issue by nurrony** [sun1x/eslint-to-editorconfig#1]
When I am running the command It is thowing following error. I have `.eslintrc`  in my current directory

``` js
~/.npm-packages/lib/node_modules/eslint-to-editorconfig/index.js:43
  if (rules['max-len'][0] > 0) {
                      ^
TypeError: Cannot read property '0' of undefined
    at maxLineLength (~/.npm-packages/lib/node_modules/eslint-to-editorconfig/index.js:43:23)
    at rulesToProps (~/.npm-packages/lib/node_modules/eslint-to-editorconfig/index.js:72:3)
    at module.exports (~/.npm-packages/lib/node_modules/eslint-to-editorconfig/index.js:96:5)
    at Object.<anonymous> (~/.npm-packages/lib/node_modules/eslint-to-editorconfig/bin.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by snanovskyi** [comment]
@nmrony Sorry for that. Didn't check rule !== undefined
Fixed. Update your npm package
